### ISSUE TITLE
Is Project Still Active?

### ISSUE THREAD

**Issue by aj-stein-nist** [halprin/retrospective#133]
You probably recall I was a fan in the past, is this still maintained? I know the public instance is still hosted, but wanted to know if recommendations and/or bug reports are welcome.

Hope you are well!

**Comment by halprin** [comment]
Hey there AJ!  This repo isn't being maintained.  😢  I'd like to say that I would fix bugs and add new features, but I really don't see that happening anytime soon.  I'm not to the point of archiving this repository though, so feel free to give me some bug reports and feature recommendation.

**Comment by aj-stein-nist** [comment]
Sigh, oh well! I will file bugs accordingly and leave it up to you. I'll close this for now then.
